
export const MOSTRAR_PRODUCTOS = 'MOSTRAR_PRODUCTOS';
export const MOSTRAR_PRODUCTO = 'MOSTRAR_PRODUCTO';
export const AGREGAR_PRODUCTOS = 'AGREGAR_PRODUCTOS';
export const EDITAR_PRODUCTOS = 'EDITAR_PRODUCTOS';
export const ELIMINARR_PRODUCTOS = 'ELIMINARR_PRODUCTOS';
